# need env: NPM_TOKEN add at to action secrets, npm token doc see https://docs.npmjs.com/about-access-tokens/
name: node-release

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    inputs:
      dry-run:
        description: 'Run npm publish with the --dry-run flag'
        default: false
        required: false
        type: boolean
      npm_version:
        description: 'tag name, if not tag will null'
        default: ''
        required: false
        type: string
      tag_name:
        description: 'tag name, if not tag will null'
        default: ''
        required: false
        type: string
      tag_changes:
        description: 'tag changes, if not tag will null'
        default: ''
        required: false
        type: string
      upload_artifact_name:
        description: 'upload artifact name'
        default: ''
        required: false
        type: string

jobs:
  build-upload:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      -
        name: Install dependencies
        run: |
          npm install
          node -v

      -
        name: Run code check
        run: |
          npm run lint
          npm test

      - name: Check Release archive
        if: ${{ inputs.upload_artifact_name != null }}
        run: |
          echo "release archive at: ${{ env.ASSET }}"
          echo " archive sha256sum at: ${{ env.ASSET }}.sha256"

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifact_name != null }}
        with:
          name: ${{ inputs.upload_artifact_name }}
          retention-days: 5
          if-no-files-found: error
          path: |
            ${{ env.ASSET }}
            ${{ env.ASSET }}.sha256

  publish-npm:
    needs:
      - build-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      -
        name: Install dependencies
        run: |
          npm install
          node -v

      - uses: JS-DevTools/npm-publish@v3
        if: ${{ inputs.verison_name != null }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ inputs.npm_version }}
          dry-run: ${{ inputs.dry-run }}
