# need env: CODECOV_TOKEN add at to action secrets
name: node-codecov

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

jobs:
  node-codecov:
    name: node-codecov
    defaults:
      run:
        shell: bash
       # working-directory: ${{ env.WORK_DIR }}
    strategy:
      matrix:
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          - 'lts/*'
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Install dependencies
        run: |
          npm install
          # npm ci
          node -v
      -
        name: Build if present
        run: |
          npm run build --if-present
      -
        name: Run lint
        run: |
          npm run lint
      -
        name: Test with node
        run: |
          npm test
      -
        name: Test coverage
        run: |
          npm run jest:coverage

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          directory: ./coverage
#          verbose: true
